### ISSUE TITLE
Taxonomy name should be Product Type

### ISSUE THREAD

**Issue by rcass** [isha21/Project-4#3]
In your functionality plugin, I noticed you registered your custom taxonomy under that name 'product' (line 44 in /plugins/inhabitent-functionality/lib/functions/taxonomies.php )

Currently, your custom post type is called product, so having them named the same is confusing.

Also, if you try creating a archive page for the product type it wont work as expected.

So a name change is in order!

- [ ] Change taxonomy name to `product-type` (line 44 in /plugins/inhabitent-functionality/lib/functions/taxonomies.php )
- [ ] Add taxonomy content (you will have to add it again and associate it with the appropriate items)

Tip: You might have to refresh your permalinks after you do the name change.

**Comment by isha21** [comment]
done
