### ISSUE TITLE
No need for single-post.php

### ISSUE THREAD

**Issue by rcass** [isha21/Project-4#4]
The starter theme out of the box came with basic blog functionality, meaning for displaying a single post is was just using single.php.

Since there there is not content/php changes needed to be done the default it fine. (You will just need to apply css).

Basically you should not need a single-post.php, since single.php exists.

- [ ] Delete single-post.php

* Here is the [template hierarchy](https://wphierarchy.com/) for reference.
* [Article](https://premium.wpmudev.org/blog/guide-wordpress-template-hierarchy/) for reference. There are more resources in the template hierarchy lesson page as well.

**Comment by isha21** [comment]
deleted

**Comment by rcass** [comment]
awesome 💯
